### ISSUE TITLE
js can never modify <textarea>'s value if its value is changed by user

### ISSUE THREAD

**Issue by rhiswell** [Ive20/ezgotranslate#2]
js can never modify `<textarea>`'s value if its value is changed by user. I prefer `<input>` instead of `<textarea>`.

**Comment by shibaozhang95** [comment]
Have been resolved.

Changed `<textarea>` to `<div contenteditable=''true">`

**Comment by rhiswell** [comment]
`contenteditable` 还有这属性? 兼容性怎么样? 我服务器 pull 过代码了,你可以不同浏览器测试...

**Comment by shibaozhang95** [comment]
支持的浏览器:
chrome 12
ie 6 8
苹果safari 5
firefox 5 (网上copy的。。。)
